name: Akamai Property Manager
on: 
  workflow_dispatch:
  push: 
    branches:
      - main
    paths:
      - 'github-actions-terraform/*'
      - '.github/workflows/akamai_pm.yaml'

jobs:
  terraform:
    name: Akamai Property Apply Terraform 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6
      - name: Add Linode S3 Backend for Terraform
        run: |
          cat << EOF > ./github-actions-terraform/backend
          skip_credentials_validation=true
          skip_region_validation=true
          bucket="${{ secrets.LINODE_OBJECT_STORAGE_BUCKET }}"
          key="tf-akamai.tfstate"
          region="us-southeast-1"
          endpoint="us-southeast-1.linodeobjects.com"
          access_key="${{ secrets.LINODE_OBJECT_STORAGE_ACCESS_KEY }}"
          secret_key="${{ secrets.LINODE_OBJECT_STORAGE_SECRET_KEY }}"
          EOF
      - name: Add Terraform TFVars
        run: |
          cat << EOF > ./github-actions-terraform/terraform.tfvars
          env="staging"
          EOF
      - name: Terraform nit
        run: terraform -chdir=./github-actions-terraform init -backend-config=backend
      - name: Terraform Validate 
        env:
          TF_VAR_akamai_client_secret: "${{ secrets.AKAMAI_CREDENTIAL_CLIENT_SECRET }}"
          TF_VAR_akamai_host: "${{ secrets.AKAMAI_CREDENTIAL_HOST }}"
          TF_VAR_akamai_access_token: "${{ secrets.AKAMAI_CREDENTIAL_ACCESS_TOKEN }}"
          TF_VAR_akamai_client_token: "${{ secrets.AKAMAI_CREDENTIAL_CLIENT_TOKEN }}"
        run: terraform -chdir=./github-actions-terraform validate -no-color
      - name: Terraform Apply Changes 
        run: terraform -chdir=./github-actions-terraform apply -auto-approve